<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>6kinokoTAS.App</AssemblyName>
        <RootNamespace>KinokoTAS.App</RootNamespace>
        <Title>6kinoko TAS</Title>
        <Product>6kinoko TAS</Product>
        <ApplicationIcon>Assets/6kinoko.ico</ApplicationIcon>
        <OutputType>WinExe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>
    <ItemGroup>
        <AvaloniaResource Include="Assets/6kinoko.ico"/>
        <ProjectReference Include="../KinokoTAS.Core/KinokoTAS.Core.csproj"/>
        <PackageReference Include="Avalonia" Version="12.1.3"/>
        <PackageReference Include="Avalonia.Desktop" Version="12.1.3"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3"/>
        <PackageReference Include="FluentIcons.Avalonia" Version="2.1.341"/>
    </ItemGroup>
</Project>
